### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by ghena** [zrrrzzt/gpagespeed#144]
When i require the library in this way
const gspeed = require('gpagespeed');
I get:
C:\wamp6\www\spider\node_modules\gpagespeed\index.js:6
  return new Promise(async (resolve, reject) => {
                           ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\wamp6\www\spider\libs\pagespeed.js:1:78)

**Comment by zrrrzzt** [comment]
Which version of node are you running? This module requires >= 8.
